
---
config:
  theme: forest
---
erDiagram
    FACT_SALES {
        INTEGER ORDER_ID
        INTEGER CUSTOMER_KEY
        INTEGER PRODUCT_KEY
        INTEGER DATE_KEY
        INTEGER COUNTRY_KEY
        INTEGER QUANTITY
        FLOAT PRICE
        FLOAT TOTAL_AMOUNT
    }

    DIM_CUSTOMER {
        INTEGER CUSTOMER_KEY
        INTEGER CUSTOMER_ID
    }

    DIM_PRODUCT {
        INTEGER PRODUCT_KEY
        STRING PRODUCT_NAME
    }

    DIM_DATE {
        INTEGER DATE_KEY
        DATE ORDER_DATE
        INTEGER YEAR
        INTEGER MONTH
        INTEGER DAY
    }

    DIM_COUNTRY {
        INTEGER COUNTRY_KEY
        STRING COUNTRY_NAME
    }

    FACT_SALES }o--|| DIM_CUSTOMER : "belongs to"
    FACT_SALES }o--|| DIM_PRODUCT : "belongs to"
    FACT_SALES }o--|| DIM_DATE : "belongs to"
    FACT_SALES }o--|| DIM_COUNTRY : "belongs to"


