/* Create a Storage Integration in Snowflake */
CREATE OR REPLACE STORAGE INTEGRATION s3_sales_integration
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::123456789012:role/snowflake-role'
STORAGE_ALLOWED_LOCATIONS = ('s3://sales-data-bucket/raw/');

/* Create a File Format */
CREATE OR REPLACE FILE FORMAT csv_format
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1;

/* Create a Stage in Snowflake */
CREATE OR REPLACE STAGE s3_sales_stage
URL = 's3://sales-data-bucket/raw/'
STORAGE_INTEGRATION = s3_sales_integration
FILE_FORMAT = csv_format;

/* Validation of stage --s3_sales_stage */
LIST @s3_sales_stage;

/* Create a RAW table for S3 */
CREATE OR REPLACE TABLE RAW_SALES (
    ORDER_ID INTEGER,
    CUSTOMER_ID INTEGER,
    ORDER_DATE DATE,
    PRODUCT STRING,
    QUANTITY INTEGER,
    PRICE FLOAT,
    COUNTRY STRING,
    TOTAL_AMOUNT FLOAT
);

/* Load data from S3
This is real data ingestion (batch load) */
COPY INTO RAW_SALES
FROM @s3_sales_stage
ON_ERROR = 'CONTINUE';

/* Transform into a Star Schema */

/* DIM_CUSTOMER */
INSERT INTO DIM_CUSTOMER (CUSTOMER_ID)
SELECT DISTINCT CUSTOMER_ID
FROM RAW_SALES;

/* DIM_PRODUCT */
INSERT INTO DIM_PRODUCT (PRODUCT_NAME)
SELECT DISTINCT PRODUCT
FROM RAW_SALES;

/* DIM_COUNTRY */
INSERT INTO DIM_COUNTRY (COUNTRY_NAME)
SELECT DISTINCT COUNTRY
FROM RAW_SALES;

/* DIM_DATE */
INSERT INTO DIM_DATE
SELECT DISTINCT
    TO_NUMBER(TO_VARCHAR(ORDER_DATE, 'YYYYMMDD')) AS DATE_KEY,
    ORDER_DATE,
    YEAR(ORDER_DATE),
    MONTH(ORDER_DATE),
    DAY(ORDER_DATE)
FROM RAW_SALES;

/* FACT_SALES */
INSERT INTO FACT_SALES
SELECT
    r.ORDER_ID,
    dc.CUSTOMER_KEY,
    dp.PRODUCT_KEY,
    dd.DATE_KEY,
    dco.COUNTRY_KEY,
    r.QUANTITY,
    r.PRICE,
    r.TOTAL_AMOUNT
FROM RAW_SALES r
JOIN DIM_CUSTOMER dc ON r.CUSTOMER_ID = dc.CUSTOMER_ID
JOIN DIM_PRODUCT dp ON r.PRODUCT = dp.PRODUCT_NAME
JOIN DIM_DATE dd ON r.ORDER_DATE = dd.ORDER_DATE
JOIN DIM_COUNTRY dco ON r.COUNTRY = dco.COUNTRY_NAME;

/* Automation (Streams + Tasks)
Stream to detect new data */
CREATE OR REPLACE STREAM raw_sales_stream
ON TABLE RAW_SALES;

/* Scheduled task */
CREATE OR REPLACE TASK load_fact_sales_task
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 0 * * * * UTC'
AS
INSERT INTO FACT_SALES
SELECT ...
FROM raw_sales_stream;

ALTER TASK load_fact_sales_task RESUME;

/* BI-ready */
SELECT
    d.YEAR,
    c.COUNTRY_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_SALES
FROM FACT_SALES f
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
JOIN DIM_COUNTRY c ON f.COUNTRY_KEY = c.COUNTRY_KEY
GROUP BY d.YEAR, c.COUNTRY_NAME
ORDER BY TOTAL_SALES DESC;
