CREATE OR REPLACE TABLE SALES (
    ORDER_ID INTEGER,
    CUSTOMER_ID INTEGER,
    ORDER_DATE DATE,
    PRODUCT STRING,
    QUANTITY INTEGER,
    PRICE FLOAT,
    COUNTRY STRING,
    TOTAL_AMOUNT FLOAT
);
